### sensors.yaml

- platform: wirelesstag
  monitored_conditions:
    - temperature
    - humidity
    - light
    # - moisture


- platform: template
  sensors:
    current_power_display:
      value_template: "{{states('sensor.current_power') | round(1)}}"
      icon_template: mdi:flash
      unit_of_measurement: 'w'
    pool_sub_power_display:
        value_template: "{{states('sensor.pool_sub_power') | round(1)}}"
        icon_template: mdi:flash
        unit_of_measurement: 'w'
    water_tank_level:
      friendly_name: "Water Tank Level"
      unit_of_measurement: '%'
      icon_template: mdi:gas-cylinder
      value_template: >
        {% set voltage = states('sensor.water_tank_voltage')|float %}
        {% if voltage > 0.50 %}
          {{((voltage - 0.59)/(1.42-0.59)*100)|round(0) }}
        {% else %}
          invalid
        {% endif %}


- platform: rest
  name: SPAN-test
  resource: http://192.168.2.59:8080/api/v1/panel
  value_template: "OK"
  # json_attributes_path: "$.branches.id"
  # json_attributes:
  #   - instantPowerW
  #   - exportedActiveEnergyWh