esphome:
  name: watertank
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: adc
    pin: A0
    name: "Water Tank Voltage"
    update_interval: 5s
    filters:
      - median:
      - multiply: 3.3


