input_boolean:
  pool_waterfall:
    name: Pool Waterfall
    icon: mdi:waterfall

automation:
  - alias: spillway_on
    description: 'Turn on spillway'
    mode: single
    trigger:
      - platform: state
        entity_id:
          - input_boolean.pool_waterfall
        from: 'off'
        to: 'on'
    condition: []
    action:
      - if:
          - condition: state
            entity_id: switch.pool
            state: 'on'
        then:
          - service: switch.turn_on
            target:
              entity_id:
                - switch.spillway
                - switch.spa_waterfall
        else:
          - if:
              - condition: state
                entity_id: switch.spa
                state: 'on'
            then:
              - service: switch.turn_on
                target:
                  entity_id: switch.spa_waterfall
              - service: switch.turn_off
                target:
                  entity_id: switch.spillway
  - alias: spillway_off
    description: 'Turn off spillway'
    mode: single
    trigger:
      - platform: state
        entity_id:
          - input_boolean.pool_waterfall
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.spillway
            - switch.spa_waterfall
